# Generated by Django 4.2.27 on 2026-01-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='time',
        ),
        migrations.AddField(
            model_name='post',
            name='authorType',
            field=models.CharField(default='cfex', max_length=4),
            preserve_default=False,
        ),
    ]
