# Generated by Django 4.2.27 on 2026-01-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_created_post_time_post_authortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.JSONField(default=list),
        ),
    ]
