# Generated by Django 4.2.27 on 2026-01-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_post_liked_by_remove_post_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='created_at',
        ),
    ]
